# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ulink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods

  # Pods for ulink
  pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'FSCalendar' 
  pod 'SnapKit', '~> 5.0.0'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'TextFieldEffects'
end
