# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ulink' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ulink
    pod 'Alamofire', '~> 4.8.2'
  pod 'Kingfisher', '~> 5.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'TextFieldEffects'
  pod 'FSCalendar'
  pod 'ObjectMapper', '~> 3.5' 
  pod 'SideMenu', '~> 6.0'
  pod 'RealmSwift' 
  pod 'SwiftyJSON','~>4.0'
  pod 'BEMCheckBox'
  pod 'lottie-ios'
  pod 'SwiftGifOrigin', '~> 1.7.0'
  pod 'GIFImageView'


end
